apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jenne
  namespace: jenne
spec:
  description: Challenge finale deploiement d'une ap en iaac
  destinations:
    - name: in-cluster
      namespace: jenne
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/O-clock-Hati/challenge-final-Jenne9.git
status: {}
